version: 0.2

env:
  variables:
    GITHUBUSERNAME: prateekchaudhry
 
phases:
  install:
    commands:
       - go version
       - architecture=""
       - case $(uname -m) in
           x86_64)
             architecture="amd64"
           ;;
           aarch64)
             architecture="arm64"
           ;;
         esac
       - GOVERSION="1.15.15"
       - BUILD_LOG="build_${architecture}.log"
       - GOLANG_TAR="go${GOVERSION}.linux-${architecture}.tar.gz"
       - wget -O /tmp/${GOLANG_TAR} https://storage.googleapis.com/golang/${GOLANG_TAR} | tee $BUILD_LOG
       - tar -C /usr/local -xzf /tmp/${GOLANG_TAR} | tee -a $BUILD_LOG
       - go version
       - echo "Install glibc-static for dockerfree installation method" | tee -a $BUILD_LOG
       - yum -y install glibc-static | tee -a $BUILD_LOG
  build:
    commands:
      - go version
      - echo "build_id = $CODEBUILD_LOG_PATH" | tee -a $BUILD_LOG
      - echo Building agent image | tee -a $BUILD_LOG
      - AGENT_VERSION=$(cat VERSION)
      - ECS_AGENT_TAR="ecs-agent-v${AGENT_VERSION}.tar"
      - echo $(pwd) | tee -a $BUILD_LOG
      # Path readjustment for codebuild testing with fork due to cni plugins - may not needed when deploying with main(?)
      - cd ../..
      - mv $GITHUBUSERNAME aws
      - cd aws/amazon-ecs-agent
      - GO111MODULE=auto
      - make dockerfree-agent-image 2>&1 | tee -a $BUILD_LOG
      # Rename arm artifact
      - |
        if [[ $architecture == "arm64" ]] ; then
          mv $ECS_AGENT_TAR "ecs-agent-arm64-v${AGENT_VERSION}.tar"
          ECS_AGENT_TAR="ecs-agent-arm64-v${AGENT_VERSION}.tar"
        fi
      # Will the arm artifacts have same name as amd artifacts?
  post_build:
    commands:
artifacts:
  files:
    - $ECS_AGENT_TAR
    - $BUILD_LOG
  name: $CODEBUILD_RESOLVED_SOURCE_VERSION
