version: 0.2

env:
  variables:
    # Github username of the forked repo on which to make builds
    GITHUBUSERNAME: prateekchaudhry
 
phases:
  install:
    commands:
       - architecture=""
       # Same buildspec for different architectures - detect the architecture here and rename the artifacts accordingly
       - case $(uname -m) in
           x86_64)
             architecture="amd64"
           ;;
           aarch64)
             architecture="arm64"
           ;;
         esac

       - echo $GOROOT
       - echo $GOPATH
       - echo $GOBIN
       - which go
       - goenv install --list
       - GOVERSION="$(cat GO_VERSION)"
       - GOVERSION="1.15.5"
       - BUILD_LOG="build_${architecture}.log"

       # Install the correct version of GoLang using goenv utility (preinstalled in CodeBuild images)
       - goenv install $GOVERSION
       - goenv local $GOVERSION
       - go version

       # glibc-static required for dockerfree make method
       - echo "Install glibc-static for dockerfree make method" | tee -a $BUILD_LOG
       - yum -y install glibc-static 2>&1 | tee -a $BUILD_LOG

  build:
    commands:
      - go version
      - echo "build_id = $CODEBUILD_LOG_PATH" 2>&1 | tee -a $BUILD_LOG
      - echo Building agent image 2>&1 | tee -a $BUILD_LOG
      - AGENT_VERSION=$(cat VERSION)
      - ECS_AGENT_TAR="ecs-agent-v${AGENT_VERSION}.tar"
      - echo $(pwd) 2>&1 | tee -a $BUILD_LOG

      # Path readjustment for codebuild testing with fork - may not needed when deploying with main account
      - cd ../..
      - mv $GITHUBUSERNAME aws
      - cd aws/amazon-ecs-agent

      - GO111MODULE=auto
      - make dockerfree-agent-image 2>&1 | tee -a $BUILD_LOG
      # Rename artifacts for architecture
      - |
        if [[ $architecture == "arm64" ]] ; then
          mv $ECS_AGENT_TAR "ecs-agent-arm64-v${AGENT_VERSION}.tar"
          ECS_AGENT_TAR="ecs-agent-arm64-v${AGENT_VERSION}.tar"
        fi

  post_build:
    commands:

artifacts:
  files:
    - $ECS_AGENT_TAR
    - $BUILD_LOG
  name: $CODEBUILD_RESOLVED_SOURCE_VERSION

